# Generated by Django 5.1.5 on 2025-02-03 21:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_email_user_email_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('loan_type', models.CharField(max_length=255)),
                ('loan_amount', models.IntegerField(default=0)),
                ('interest_rate', models.FloatField()),
                ('term_period', models.IntegerField(default=0)),
                ('disbursement_date', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user', to_field='user_id')),
            ],
        ),
    ]
