# Generated by Django 5.1.5 on 2025-02-04 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_billing_duepayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='user',
        ),
        migrations.RemoveField(
            model_name='duepayment',
            name='user',
        ),
        migrations.AddField(
            model_name='billing',
            name='loan',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to='api.loan', to_field='loan_id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='duepayment',
            name='loan',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to='api.loan', to_field='loan_id'),
            preserve_default=False,
        ),
    ]
