# Generated by Django 5.1.5 on 2025-02-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='loan',
            new_name='loan_id',
        ),
    ]
