# Generated by Django 5.1.5 on 2025-02-04 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_loan_payment_loan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='loan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.loan', to_field='loan_id'),
        ),
    ]
